[package]
name = "LongArithmetics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
byteorder = "1.4.3"
bytemuck = "1.13.1"